name: WakaTime workflow file

on:
  schedule:
    # Runs at 00:00 GMT+4 Azerbaijan time
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "whtmst_waka_info" # flag can be set to any string, and will be the name of the section to replace in the readme
          LOCALE: "en" # en, ru, az, uk & etc. | more info - https://saimana.com/list-of-country-locale-code/
          COMMIT_BY_ME: "False" # flag can be set to True to commit the code using your name and email
          COMMIT_MESSAGE: "Updated by Wht Mst" # flag can be set to message commit, default is "Updated with Dev Metrics"
          COMMIT_USERNAME: "Wht Mst" # flag can be set to username to commit the code, default is "readme-bot"
          COMMIT_EMAIL: "wht.mst.official@gmail.com" # flag can be set to email to commit the code, default is "41898282+github-actions[bot]@users.noreply.github.com"
          SHOW_UPDATED_DATE: "False" # flag can be set to True to show updated date in end of paragraph
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S" # flag can be set to put updated date into a format, default is "%d/%m/%Y %H:%M:%S"
          SHOW_LINES_OF_CODE: "False" # flag can be set to True to show the Lines of code writen till date
          SHOW_TOTAL_CODE_TIME: "False" # flag can be set to False to hide Code Time
          SHOW_PROFILE_VIEWS: "False" # flag can be set to False to hide the Profile views
          SHOW_COMMIT: "False" # flag can be set to False to hide the commit stats
          SHOW_DAYS_OF_WEEK: "False" # flag can be set to False to hide the commits made on different days of week
          SHOW_LANGUAGE: "True" # flag can be set to False to hide the Coding Language You use
          SHOW_OS: "True" # flag can be set to False to hide the OS details
          SHOW_PROJECTS: "False" # flag can be set to False to hide the Projects worked on
          SHOW_TIMEZONE: "True" # flag can be set to False to hide the time zone you are in
          SHOW_EDITORS: "True" # flag can be set to False to hide the list of code-editors used
          SHOW_LANGUAGE_PER_REPO: "False" # flag can be set to False to hide the Number of repository in different language and frameworks
          SHOW_SHORT_INFO: "False" # flag can be set to False to hide the short fun fact info of user
          SHOW_LOC_CHART: "False" # flag can be set to False to hide the Lines of code written in different quarters of different year
          IGNORED_REPOS: "my-first-repo, my-second-repo" # flag can be set to "waka-readme-stats, my-first-repo" (just an example) to ignore some repos you don’t want to be counted
          SYMBOL_VERSION: "2" # flag can be set symbol for progress bar (default: 1) Example - 1: Done block █ Empty block ░ / 2: Done block ⣿ Empty block ⣀ / 3: Done block ⬛ Empty block ⬜